# Setup
version_name: nyud 
out_dir: "./"

# Database
train_db_name: NYUD
val_db_name: NYUD
trBatch: 2
valBatch: 6
#nworkers: 2
nworkers: 0
ignore_index: 255

# Optimizer and scheduler
intermediate_supervision: True
val_interval: 1000
epochs: 999999
max_iter: 40000
optimizer: adam
optimizer_kwargs:
   lr: 0.00002
   weight_decay: 0.000001
scheduler: poly

# Model
model: TransformerNet
backbone: tspL
head: mlp
embed_dim: 512
mtt_resolution_downsample_rate: 2
PRED_OUT_NUM_CONSTANT: 64

#Task prompts
prompt_nums: 5
prompt_layers: 12
prompt_insertype: Deep

# Tasks
task_dictionary:
   include_semseg: True
   include_depth: True
   include_edge: True
   include_normals: True
   edge_w: 0.95

# Loss kwargs
loss_kwargs:
   loss_weights:
       semseg: 1.0
       depth: 1.0
       normals: 10
       edge: 50.0
